apiVersion: apps/v1
kind: Deployment
metadata:
  name: ga
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ga
  template:
    metadata:
      labels:
        app: ga
    spec:
      containers:
        - name: ga
          image: ckcks12/deep-whale-ga
          env:
            - name: DB_HOST
              value: whale.eunchan.com
            - name: DB_PORT
              value: 9354
            - name: DB_USER
              value: uBVj64aCvFEMtb
            - name: DB_PASSWORD
              value: Sn6KNYWrQDCn68
            - name: DB_NAME
              value: postgres
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              port: 80
              path: /health
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              port: 80
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 3
